project_id = "aqbyqtvaxjroakgnxlun"

[functions.validate-media]
verify_jwt = false

[functions.match-context]
verify_jwt = false

[functions.manage-credentials]
verify_jwt = true

[functions.get-heygen-credits]
verify_jwt = true
